### ISSUE TITLE
does it work and if yes, how?

### ISSUE THREAD

**Issue by shelmz** [gathertown/grapes#1]
This seems very interesting! Unfortunately the documentation did not allow me to use Grapes - is it supposed to work already?

If yes, could you please explain which version of gather-**game-client** and **gather-game-common** do I refer to in *packages.json* to get it to work? I already set up the **API_KEY** in **environment.d.ts** and the **start script** for Node:
` "start": "tsc -b && node dist/src/index.js",`

I have tried each of the last two versions of ***-client** and ***-common** but I still get error messages which looks like I don't use the right dependency versions.

Furthermore I would like to understand how to pass the commands in the end? it seems that only _.txt_ files in a directory - maybe in _/src_ (?) - are sufficient to get it to work.

**Comment by npfoss** [comment]
it doesn't work yet sorry, this was an internal prototype that's accidentally public!

**Comment by shelmz** [comment]
okay pity, but not too bad - thanks for the info! :-)
